TREND-0031
AgustinBettati/trendz pull request #39
Opened 2020-10-09 20:54 UTC by sofiasdz

ISSUE-0194 and ISSUE-0191

2020-10-11 20:01 UTC, gdeachaval requested changes
@sofiasdz post comment is not working, server is receiving empty content. Also, topic page should not be refreshed in order for new comment to appear: client should manage state to solve this

2020-10-13 17:43 UTC, marcoskhabie requested changes

2020-10-13 17:43 UTC, marcoskhabie commented on client/src/components/Post/Post.tsx
> +            comments.push(commentArray);
This should not be hardcoded. We should push the new comment to the state of comments. Also please use let instead of var.

2020-10-13 20:19 UTC, gdeachaval approved these changes

2020-10-13 20:21 UTC, marcoskhabie approved these changes

2020-10-13 20:22 UTC, merged